### PR TITLE
Update fork from rock-core

### PR DESCRIPTION
**Pull request by romulogcerqueira**

### CODE REVIEW

**Comment by doudou** [comment]
@romulogcerqueira: best is really to not do pull requests to update from rock-core. I actually believe that we don't need to have our own fork from now on. Could you check that and remove the override in the buildconf ?

**Comment by romulogcerqueira** [comment]
@doudou , to create pull requests for rock-core, we need to fork the desired repository before with the candidate branch. Do you prefer that I fork the base/types to my own github account instead of BIR one?

**Comment by doudou** [comment]
@romulogcerqueira: not what I meant

Once you have it merged on rock-core, don't bother with a PR on our BIR fork. This creates a merge commit, and the next time you create a PR for rock-core based on our fork, it will include the merge. It means that you create at least two merge commits per PR .... :P

**Comment by romulogcerqueira** [comment]
I got your point.

I will follow this way.

**Pull request merged**
